'''
1. 假设有一个仓库结构为:

   ```
   .github/workflow/build.yml
   src/... (c++文件及头文件)
   ```

  完成build.yml的相关内容，使该仓库能够在每次提交时编译源代码并上传可执行文件。
'''
name: Build and Upload

on: [push] # Trigger the workflow on push event 每次提交时，编译源代码并上传可执行文件

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
    - name: Checkout repository # Checkout the repository to the runner 检出存储库到runner
      uses: actions/checkout@v2 #使用actions/checkout@v2

    - name: Set up C++ environment # Set up the C++ compiler environment
      uses: actions/setup-cpp@v1
      with:
        compiler: gcc # Use the latest version of GCC

    - name: Install dependencies
      run: sudo apt-get install -y build-essential # Install the build-essential package

    - name: Build the project # Build the project using CMake
      run: |
        mkdir build
        cd build
        cmake ..
        make 

    - name: Upload artifact # Upload the executable file as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: build/3DConstructer # Upload the executable file
